#!/bin/sh
set -e

service_down () {
	name="$1"
	if systemctl is-enabled "$name" >/dev/null; then
		echo "Disabling $name..."
		systemctl disable --now "$name" || true
	fi
}

if [ "$1" = "remove" ]; then
	service_down solarnode-bt-setup-peripheral-restart.path
	service_down solarnode-bt-setup-peripheral
	# the peripheral is normally disabled but may be running on demand
	if [ -x /usr/share/solarnode/cfg.d/bluetooth.sh ]; then
		/usr/share/solarnode/cfg.d/bluetooth.sh disable || true
	fi
fi
